on:
  push:
    branches:
      - main
  pull_request:

name: Test
jobs:
  lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4.1.2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run vet
        run: go vet ./...

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2.6
 